language: node_js
node_js:
  - "6"
  - "node"

sudo: false

branches:
  only: master

after_script:
  - istanbul cover node_modules/mocha/bin/_mocha server/tests/**/*.spec.js -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
